arnia-linkcom-gamification/Frontend-Culture-Code

package-lock.json, package.json, src/App.tsx
Foi instalada a Biblioteca React Router Dom  e Styled Components
=> Feature:  React Router Dom  e Styled Components

package-lock.json, package.json, src/App.tsx
Reverts arnia-linkcom-gamification/Frontend-Culture-Code#15
=> Revert "Feature:  React Router Dom  e Styled Components"

src/components/Button/Button.Styled.tsx, src/components/Button/Button.tsx
=> Feature: ButtonProps

package-lock.json, package.json, src/components/Button/Button.Styled.tsx, src/components/Button/Button.tsx, src/components/CardLogin/CardLogin.tsx, src/components/CardLogin/CardLoginStyled.tsx, src/components/FormLogin/FormLogin.tsx, src/components/FormLogin/FormLoginStyled.tsx, src/pages/Login/Login.tsx, src/pages/Login/LoginStyled.tsx, src/routes/Rotas.tsx, src/schemas/schameogin.tsx
Realizei a instalação da biblioteca **Frame- motion**  para realizar as animações , porem assim que realizei a instalação da mesma, tive que reinstalar novamente as bibliotecas React Router Dom e a Styled Components porque ocorreu uma incopatibilidade nas versões, Mas foi resovido e a aplicação está funcionando normalmente.
=> Feature: Construção  dos cards das Telas de Login desktop e  mobile

src/components/CardPerfil/CardPerfil.Styled.tsx, src/components/CardPerfil/CardPerfil.tsx, src/components/Navigation/Navigation.Styled.tsx, src/components/Navigation/Navigation.tsx, src/pages/Home/Home.tsx, src/pages/Products/Products.tsx, src/routes/Rotas.tsx
Foi realiza a implementação da página de Produtos.
OBS: Foi realizada uma correção no cardPerfil  para que a cor dos texto se adaptem entre as páginas do layout , e foi implementado também no componente navigation um alteração
=> Page Products

src/components/CardProductsRedeems/CardProductsRedeems.Styled.tsx, src/components/CardProductsRedeems/CardProductsRedeems.tsx, src/components/CardRedeemFor/CardRedeemFor.Styled.tsx, src/components/CardRedeemFor/CardRedeemFor.tsx, src/pages/Products/Products.Styled.tsx, src/pages/Products/Products.tsx
=> Feature: Foi  implementado o cardProductsRedeems e o CardRedeemFor

src/components/CardSmallProductsSuccess/CardSmallProductsSuccess.Styled.tsx, src/components/CardSmallProductsSuccess/CardSmallProductsSuccess.tsx, src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.Styled.tsx, src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.tsx
Foi realizado a criação do  card small product success
=> Feature: implementação do card small product success

src/components/Button/Button.Styled.tsx, src/components/Button/Button.tsx, src/components/CardProductsRedeems/CardProductsRedeems.tsx, src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.tsx, src/components/FormLogin/FormLogin.tsx, src/components/cardProduct/cardProduct.tsx, src/pages/Login/Login.tsx
Foi implementado a props border
=> Feature: implementação da  props border

src/components/CardProductsRedeems/CardProductsRedeems.tsx, src/components/cardProduct/cardProduct.tsx, src/pages/Products/Products.tsx
foi implementado o onclick e a lógica para mudar os cards   CardSuccessfullyRescued   e CardProductsRedeems
=> Feature: Implementação do onClick

src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.Styled.tsx, src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.tsx, src/pages/Products/Products.Styled.tsx, src/pages/Products/Products.tsx
Foi implementado a animação entre os cards  CardSuccessfullyRescued eo CardProductsRedeems
=> Feature: Implementação de animação

package-lock.json, package.json
Foi realizado a instalação da biblioteca useQuery
https://tanstack.com/query/v4/docs/framework/react/installation
=> Feature: Use query

.env, package-lock.json, package.json, src/components/Button/Button.tsx, src/components/FormLogin/FormLogin.tsx, src/hooks/axios/api.tsx, src/main.tsx, src/services/auth/loginUser.tsx
Foi implementado a instalação da biblioteca useQuery e implementação da api login
=> Feature: Instalação da biblioteca useQuery e implementação da api login

src/App.tsx, src/components/FormLogin/FormLogin.tsx, src/context/userContext.tsx, src/routes/Rotas.tsx, src/services/auth/SecurityToken.tsx
Foi realizado a implementação do context TokenContext, para garantir a segurança das rotas privadas do sistema
=> Feature: implementação do context TokenContext

src/provider/SecurityToken.tsx, src/routes/Rotas.tsx, src/services/auth/loginUser.tsx
Foi realizado uma troca de arquivo, SecurityToken que estava na pasta service para a pasta provider.
E a criação da pasta ggetUser
=> Fix: trocar de arquivos de pasta

src/components/CardBalance/CardBalance.tsx, src/components/CardPerfil/CardPerfil.tsx, src/hooks/axios/api.tsx, src/services/auth/loginUser.tsx, src/services/getUser/getUser.tsx, src/types/getUsers/getUsers.tsx
Foi implementado um novo endpoint getUser para facilitar a obtenção dos dados do usuário atualmente autenticado no sistema. Essa adição permitirá que o frontend acesse informações detalhadas do usuário, como nome, e-mail e outros dados relevantes.
Para implementar essa funcionalidade, aproveitei a biblioteca useQuery do pacote @tanstack/react-query. A escolha por essa abordagem visa simplificar a gestão de requisições assíncronas, garantindo uma integração eficiente entre o frontend e o backend.
Ao utilizar useQuery, conseguimos realizar chamadas à API de maneira eficaz, automatizando a atualização do estado do componente quando os dados do usuário são recuperados. Essa abordagem não apenas melhora a experiência do usuário, mas também torna o código mais claro e fácil de manter.
=> Feature: implementação do endpoint getUser

src/components/CardPerfil/CardPerfil.tsx, src/components/Navigation/Navigation.tsx, src/components/cardProduct/cardProduct.tsx, src/pages/Home/Home.tsx, src/routes/Rotas.tsx, src/services/getProducts/getProducts.tsx, src/types/getProducts/getProducts.tsx
Foi concluída a implementação do endpoint 'getProducts', que envolveu a integração com uma API para obter dados dinâmicos. O componente 'cardProducts' foi aprimorado através da aplicação de um mapeamento, permitindo uma exibição dinâmica dos produtos.
Além disso, houve uma modificação na rota 'produtos', agora incluindo um parâmetro 'id' para identificação específica do produto. A lógica de verificação de rota foi ajustada para determinar a rota atual, possibilitando a alteração da cor do nome do usuário de acordo com a rota em que se encontra. Para isso, foi adicionada a condição 'location.pathname.startsWith' no processo de verificação.
=> Feature: implementação do endpoint getProducts

src/components/CardPerfil/CardPerfil.tsx, src/components/cardProduct/CardProductStyled.tsx, src/pages/Home/Home.tsx
Foi realizada uma correção de responsividade no Card Products
=> Fix: correção de responsividade no card-Products

src/components/ProfileCardChangePassword/ProfileCardChangePassword.tsx, src/components/ProfileCardChangePassword/ProfileCardChangePasswordStyle.tsx, src/components/ProfileMenu/ProfileMenu.tsx, src/pages/Perfil/Perfil.tsx
Criação da tela de alteração de senha de forma estática, com versão web e mobile.
=> Feature: Criação da tela de alteração de senha

src/components/CardMyBalance/CardMyBalance.Styled.tsx, src/components/CardMyBalance/CardMyBalance.tsx, src/components/CardProductsRedeems/CardProductsRedeems.Styled.tsx, src/components/CardProductsRedeems/CardProductsRedeems.tsx, src/components/CardRedeemFor/CardRedeemFor.tsx, src/components/CardSmallProductsSuccess/CardSmallProductsSuccess.tsx, src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.tsx, src/pages/Home/Home.tsx, src/services/getProducts/getProductsId.tsx, src/types/getProducts/TypesGetProductsId.tsx
foi realizado a implementação do endPoint getProductsId
=> Feature: Implementação do endpoint  getProductsId

package-lock.json, package.json, src/components/Button/Button.Styled.tsx, src/components/Button/Button.tsx, src/components/Modal/ModalEdit.tsx, src/components/ModalConfirmationRescued/ModalConfirmationRescued.Styled.tsx, src/components/ModalConfirmationRescued/ModalConfirmationRescued.tsx, src/pages/Products/Products.tsx
Foi concluída a implementação do modal utilizando a biblioteca "react-modal", permitindo a criação de modais editáveis que podem ser reutilizados em diferentes componentes e adaptados a vários layouts. O componente ModalEdit foi desenvolvido para possibilitar a construção do componente ModalConfirmationRescued. Este último é utilizado para confirmar o resgate de um produto, oferecendo uma solução flexível e reutilizável em diferentes partes da aplicação.
=> Feature: implementação do componente  Modal 

src/components/CardPerfil/CardPerfil.tsx, src/components/CardProductsRedeems/CardProductsRedeems.tsx, src/components/ModalConfirmationRescued/ModalConfirmationRescued.tsx, src/pages/Home/Home.tsx, src/pages/Products/Products.tsx, src/services/Products/getProducts/getProducts.tsx, src/services/Products/getProducts/getProductsId.tsx, src/services/Products/productrescued/ProductRescued.tsx
Foi implementado a função 'handleRescue' , que realiza o resgate do produto que o usuário selecionou.
=> Feature: implementação da função handleRescue

src/components/Navigation/Navigation.tsx, src/components/ProfileCardChangePassword/ProfileCardChangePassword.tsx, src/components/ProfileCardProductRedeems/ProfileCardProductRedeems.tsx, src/components/ProfileCardUser/ProfileCardUser.tsx, src/components/ProfileMenu/ProfileMenu.tsx, src/pages/Perfil/Perfil.tsx, src/pages/Products/Products.tsx, src/pages/ProductsRescued/ProductsRescued.Styled.tsx, src/pages/ProductsRescued/ProductsRescued.tsx, src/routes/Rotas.tsx
Foi concluída a implementação da página 'Products Rescued'. Esta página foi criada como uma funcionalidade de recomendação, permitindo aos usuários visualizarem e resgatarem os produtos recomendados especificamente para eles. A adição desta página visa proporcionar uma experiência mais personalizada e direcionada, oferecendo aos usuários sugestões relevantes e facilitando o processo de resgate de produtos.
=> Feature: implementação da página de recomendações de resgates

src/components/Search/Search.tsx, src/pages/Home/Home.tsx, src/pages/ProductsRescued/ProductsRescued.tsx, src/services/Products/getProducts/getProducts.tsx
Implementação da Função de Busca
**Descrição:**
Este pull request introduz a implementação da função de busca, proporcionando uma funcionalidade crucial para os usuários localizarem produtos facilmente dentro do aplicativo. A função de busca permitirá que os usuários insiram termos de pesquisa e obtenham resultados relevantes de produtos.
Principais Alterações:
Adição do componente de pesquisa (Search) que inclui um campo de entrada para os usuários inserirem consultas.
Atualização da lógica no componente Home para interagir com a função de busca em tempo real.
Integração do serviço de API getProducts para buscar produtos com base nos termos de pesquisa fornecidos pelos usuários.
Melhorias Adicionais:
=> Feature: implementação da função search

package-lock.json, package.json, src/components/CardProductsRedeems/CardProductsRedeems.tsx, src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.tsx, src/components/cardProduct/cardProduct.tsx, src/hooks/axios/api.tsx, src/pages/Home/Home.tsx, src/pages/ProductsRescued/ProductsRescued.tsx, src/services/Products/getProducts/getProducts.tsx, src/types/getProducts/TypesGetProductsId.tsx, src/types/getProducts/getProducts.tsx
Foi realizada a criação da função pagination .
=> Feature: implementação da funcão Pagination

src/components/CardSmallProductsSuccess/CardSmallProductsSuccess.tsx, src/components/CardSuccessfullyRescued/CardSuccessfullyRescued.tsx, src/components/ModalPrice/ModalPrice.Styeld.tsx, src/components/ModalPrice/ModalPrice.tsx, src/components/ProfileCardJewels/ProfileCardJewels.tsx, src/components/Search/Search.Styled.tsx, src/components/Search/Search.tsx, src/components/cardProduct/CardProductStyled.tsx, src/pages/Home/Home.Styled.tsx, src/pages/Home/Home.tsx, src/pages/Products/Products.tsx, src/pages/ProductsRescued/ProductsRescued.Styled.tsx, src/pages/ProductsRescued/ProductsRescued.tsx, src/services/Products/getProducts/getProducts.tsx
foi implementado  o modal price , para que o usuário possa pesquisar os produtos  pele seus preços
=> Feature: implementação do modal ModalPrice

src/components/cardProduct/CardProductStyled.tsx, src/pages/Home/Home.tsx, src/pages/ProductsRescued/ProductsRescued.tsx, src/services/Products/getProducts/getProducts.tsx
Foi removido o componente da paginação da home e acrescentado o botão de ver mais.
=> Chore: remoção da paginação da home

src/services/Products/productrescued/ProductRescued.tsx
Foi identificado um problema na função `ProductRescued`, onde ocorria um erro de não autorização ao tentar resgatar o produto escolhido pelo usuário. Para solucionar esse problema, foi realizada uma correção que consistiu na adição de um objeto `vazio` e do objeto `headers`. Essa atualização foi essencial para garantir o funcionamento perfeito da função, permitindo agora o resgate adequado do produto pelo usuário.
Agradecemos a revisão e feedback da comunidade!
- Adição de um objeto `vazio` e do objeto `headers` na função `ProductRescued`.
=> Fix: Correção na função ProductRescued
